efs/efs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

efs/portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, register_converter
from rest_framework.urlpatterns import format_suffix_patterns
from . import converter
# from .views import PasswordResetConfirmView,ChangePasswordResetDoneSuccessView, ChangePasswordResetDoneView,PasswordResetView,PasswordResetCompleteView, PasswordResetDoneView, PasswordResetConfirmView

register_converter(converter.FloatUrlParameterConverter, 'float')
app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer/new/', views.customer_new, name='customer_new'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),
    path('stock/new/', views.stock_new, name='stock_new'),
    path('investment_list', views.investment_list, name='investment_list'),
    path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
    path('investment/new/', views.investment_new, name='investment_new'),
    path('customer/<int:pk>/portfolio/', views.portfolio, name='portfolio'),
    url(r'^customers_json/', views.CustomerList.as_view()),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('accountpreferences/', views.CustomUserChangeForm, name='accountpreferences'),
    path('reset_confirmation/<uidb64>/<token>', views.PasswordResetConfirmView.as_view(), name='reset_password_confirmation'),
    path('reset_password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password/done/', views.PasswordResetDoneView.as_view(), name='reset_password_done'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='reset_password_complete'),
    path('password_change/', views.ChangePasswordResetDoneView.as_view(), name='password_change'),
    path('password/', views.ChangePasswordResetDoneView.as_view(), name='password'),
    path('change_password_done/', views.ChangePasswordResetDoneSuccessView.as_view(), name='change_password_done'),
    path('account_profile', views.account_profile, name='account_profile'),
    path('account_profile_edit/<int:pk>', views.account_profile_edit, name='account_profile_edit'),
    path(r'broadcast/<int:pk>/<str:phonenumber>/<float:initalstock>/<float:currentstock>/<float:initalinvestment>/<float:currentinvestment>/send/', views.broadcast_sms, name="broadcast"),
    path('sendpdfEmail/<int:pk>/portfolio/', views.sendpdfEmail, name='sendpdfEmail'),
    path('downloadPDF/<int:pk>/portfolio/', views.downloadPDF, name='downloadPDF'),
    path('customer/<int:pk>/', views.CustomerByNumber.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

efs/portfolio/models.py
from django.db import models
from django.utils import timezone
import requests

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)

    def indianrupee(self):
        url = 'https://api.exchangeratesapi.io/latest?base=USD'
        json_data = requests.get(url).json()
        open_price = float(json_data["rates"]["INR"])
        indianrupee_value = open_price
        return indianrupee_value

    def gbp(self):
        url = 'https://api.exchangeratesapi.io/latest?base=USD'
        json_data = requests.get(url).json()
        open_price = float(json_data["rates"]["GBP"])
        gbp_value = open_price
        return gbp_value


class Investment(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='investments')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now, blank=True, null=True)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_investment(self):
        return self.recent_value - self.acquired_value

class Stock(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='stocks')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField (max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def initial_stock_value(self):
        return self.shares * self.purchase_price


    def current_stock_price(self):
        symbol_f = str(self.symbol)
        main_api = 'http://api.marketstack.com/v1/eod?'
        api_key = 'access_key=7f712baa95c8525de960412488da055b&limit=1&symbols='
        url = main_api + api_key + symbol_f
        json_data = requests.get(url).json()
        open_price = float(json_data["data"][0]["open"])
        share_value = open_price
        return share_value


    def current_stock_value(self):
        return float(self.current_stock_price()) * float(self.shares)

efs/portfolio/forms.py
from django import forms
from .models import Customer, Stock, Investment
from users.models import CustomUser
from django.contrib.auth.forms import PasswordResetForm, ReadOnlyPasswordHashField

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)

class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)

class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = ('customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value','recent_date',)

class CustomPasswordResetForm(PasswordResetForm):

    class Meta:
        model = CustomUser
        fields = ('email')

efs/portfolio/views.py
import decimal
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives
from django.db.models.functions import Round
from django.shortcuts import render
from django.template.loader import get_template

from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render, redirect
from django.contrib.auth import views as auth_views, forms as auth_forms
from django.db.models import Sum
from .serializers import CustomerSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import render, redirect
from django.urls import reverse,reverse_lazy
from users.forms import CustomUserCreationForm, CustomUserChangeForm
from users.models import CustomUser
from django.views import generic
from django.conf import settings
from django.http import HttpResponse
from twilio.rest import Client
from io import BytesIO
from xhtml2pdf import pisa

now = timezone.now()
def home(request):
   return render(request, 'portfolio/home.html',
                 {'portfolio': home})

@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',
                 {'customers': customer})

@login_required
def customer_edit(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   if request.method == "POST":
       # update
       form = CustomerForm(request.POST, instance=customer)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.updated_date = timezone.now()
           customer.save()
           return redirect('portfolio:customer_list')
   else:
        # edit
       form = CustomerForm(instance=customer)
   return render(request, 'portfolio/customer_edit.html', {'form': form})

@login_required
def customer_delete(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   customer.delete()
   return redirect('portfolio:customer_list')

@login_required
def stock_list(request):
   #stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
   stocks = Stock.objects.all()
   return render(request, 'portfolio/stock_list.html', {'stocks': stocks})

@login_required
def stock_edit(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   if request.method == "POST":
       form = StockForm(request.POST, instance=stock)
       if form.is_valid():
           stock = form.save()
           # stock.customer = stock.id
           stock.updated_date = timezone.now()
           stock.save()
           return redirect('portfolio:stock_list')
   else:
       # print("else")
       form = StockForm(instance=stock)
   return render(request, 'portfolio/stock_edit.html', {'form': form})

@login_required
def stock_delete(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   stock.delete()
   return redirect('portfolio:stock_list')

@login_required
def investment_list(request):
    investments = Investment.objects.all()
    return render(request, 'portfolio/investment_list.html', {'investments': investments})


@login_required
def investment_new(request):
    if request.method == "POST":
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.created_date = timezone.now()
            investment.save()
            return redirect('portfolio:investment_list')
    else:
        form = InvestmentForm()
        # print("Else")
    return render(request, 'portfolio/investment_new.html', {'form': form})

@login_required
def investment_edit(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    if request.method == "POST":
        form = InvestmentForm(request.POST, instance=investment)
        if form.is_valid():
            investment = form.save()
            investment.updated_date = timezone.now()
            investment.save()
            return redirect('portfolio:investment_list')
    else:
        # print("else")
        form = InvestmentForm(instance=investment)
    return render(request, 'portfolio/investment_edit.html', {'form': form})

@login_required
def investment_delete(request, pk):
   investment = get_object_or_404(Investment, pk=pk)
   investment.delete()
   return redirect('portfolio:investment_list')

@login_required
def stock_new(request):
   if request.method == "POST":
       form = StockForm(request.POST)
       if form.is_valid():
           stock = form.save(commit=False)
           stock.created_date = timezone.now()
           stock.save()
           stocks = Stock.objects.all()
           return render(request, 'portfolio/stock_list.html',
                         {'stocks': stocks})
   else:
       form = StockForm()
       # print("Else")
   return render(request, 'portfolio/stock_new.html', {'form': form})

@login_required
def customer_new(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.created_date = timezone.now()
            customer.save()
            customer = Customer.objects.all()
            #context= {'customers': customer}
            return redirect('portfolio:customer_list')
            #return redirect(reverse('portfolio:customer_list'),context)
            #return HttpResponseRedirect(reverse('portfolio:customer_list'), context)
    else:
        form = CustomerForm()
    return render(request, 'portfolio/customer_new.html', {'form': form})

@login_required
def portfolio(request,pk):
   customer = get_object_or_404(Customer, pk=pk)
   customers = Customer.objects.filter(created_date__lte=timezone.now())
   investments =Investment.objects.filter(customer=pk)
   stocks = Stock.objects.filter(customer=pk)
   sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
   sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
   #overall_investment_results = sum_recent_value-sum_acquired_value
   # Initialize the value of the stocks
   sum_current_stocks_value = 0.00
   sum_of_initial_stock_value = 0.00
   customer_phoneNumber = customer.cell_phone
   indianrupee_value = customer.indianrupee()
   gbp_value = customer.gbp()

   # Loop through each stock and add the value to the total
   for stock in stocks:
        currentvalue = float(stock.current_stock_price()) * float(stock.shares)
        sum_current_stocks_value += round(currentvalue,2)
        sum_of_initial_stock_value += round(float(stock.initial_stock_value()), 2)
        stock.current_stock_value = round(decimal.Decimal(stock.current_stock_price()) * decimal.Decimal(stock.shares),2)
        stock.result = round(decimal.Decimal(stock.current_stock_value) - decimal.Decimal(stock.initial_stock_value()), 2)
        stock.result_indianrupee = round((decimal.Decimal(stock.current_stock_value) - decimal.Decimal(stock.initial_stock_value())) * decimal.Decimal(indianrupee_value), 2)
        stock.result_gbp = round((decimal.Decimal(stock.current_stock_value) - decimal.Decimal(stock.initial_stock_value())) * decimal.Decimal(gbp_value), 2)

   sum_of_initial_investment_value = 0.00
   sum_current_investment_value = 0.00

   for investment in investments:
        sum_of_initial_investment_value += round(float(investment.acquired_value), 2)
        sum_current_investment_value += round(float(investment.recent_value), 2)
        investment.result = round(decimal.Decimal(investment.recent_value) - decimal.Decimal(investment.acquired_value), 2)
        investment.result_indianrupee = round((decimal.Decimal(investment.recent_value) - decimal.Decimal(investment.acquired_value)) * decimal.Decimal(indianrupee_value), 2)
        investment.result_gbp = round((decimal.Decimal(investment.recent_value) - decimal.Decimal(investment.acquired_value)) * decimal.Decimal(gbp_value), 2)


   sum_of_result_of_stock_value = round(decimal.Decimal(sum_current_stocks_value) - decimal.Decimal(sum_of_initial_stock_value), 2)
   sum_of_result_of_investment_value = round(decimal.Decimal(sum_current_investment_value) - decimal.Decimal(sum_of_initial_investment_value), 2)


   return render(request, 'portfolio/portfolio.html', {'customers': customers,
                                                       'investments': investments,
                                                       'stocks': stocks,
                                                       'sum_acquired_value': sum_acquired_value,
                                                       'sum_recent_value': sum_recent_value,
                                                        'sum_current_stocks_value': sum_current_stocks_value,
                                                        'sum_of_initial_stock_value': sum_of_initial_stock_value,
                                                        'sum_of_result_of_stock_value': sum_of_result_of_stock_value,
                                                       'sum_current_investment_value': sum_current_investment_value,
                                                       'sum_of_initial_investment_value': sum_of_initial_investment_value,
                                                       'sum_of_result_of_investment_value': sum_of_result_of_investment_value,
                                                       'customerid': pk,
                                                       'customer_phoneNumber': customer_phoneNumber})

class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm

efs/portfolio/templates/portfolio/accountprofile.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}


  <div class="ui main">
        <div class="page-container">
        <h2 style="margin-left:20%;">Account Information</h2>

        <div style="margin-left:20%;" >

             <table style="width:50%;" class="table table-striped table-bordered table-hover">

                <tbody>
                        <tr>
                            <td style="width:5%;" align="right">Username:</td><td style="width:20%;">{{customuser.username}}</td>
                        </tr>
                        <tr>
                            <td style="width:5%;" align="right">First Name:</td><td style="width:20%;">{{customuser.first_name}}</td>
                        </tr>
                        <tr>
                            <td style="width:5%;" align="right">Last Name:</td><td style="width:20%;">{{customuser.last_name}}</td>
                        </tr>
                        <tr>
                            <td style="width:5%;" align="right">Email:</td><td style="width:20%;">{{customuser.email}}</td>
                        </tr>


                      <tr>
                            <td></td>
                            <td align="center">
                                <p>
                                    <a class="btn btn-primary" href="{% url 'portfolio:account_profile_edit' pk=customuser.pk %}" role="button">Edit Information</a>
                                 </p>
                            </td>
                        </tr>

                </tbody>

                </table>


        </div>
        </div>
        </div>





{% endblock %}

efs/portfolio/templates/portfolio/accountprofile_edit.html
    {% extends 'portfolio/base.html' %}
    {% load static %}
    {% load crispy_forms_tags %}
    {% block content %}
    <div class="row justify-content-center">
                         <div class="ui main col col-md-6 mt-5">
        <h1>Edit Profile Information</h1>
        <form method="POST" class="StaffProfileEditForm">{% csrf_token %}
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="save btn btn-success">Update</button>
        </form>
    </div>
    </div>
    {% endblock %}

efs/portfolio/templates/portfolio/change_password.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Reset Password{% endblock %}

{% block content %}
<h1>Change Password</h1>

<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="save btn btn-primary">Save changes</button>
</form>
{% endblock %}

efs/portfolio/templates/portfolio/customer_delete.html
{% extends 'portfolio/base.html' %}
{% block body_block %}
    <h1>Delete {{ customer.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'portfolio:home' pk=customer.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

efs/portfolio/templates/portfolio/customer_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


    <h1>Add New Customer</h1>
       <form action="" method="post">{% csrf_token %}
       {{ form|crispy }}
        <button type="submit" class="save btn btn-primary">Add</button>
    </form>
</body>
{% endblock %}

efs/portfolio/templates/portfolio/investment_delete.html
{% extends 'portfolio/base.html' %}
{% block body_block %}
    <h1>Delete ?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'portfolio:home' pk=investment.cust_number %} ">Cancel</a>
    </form>
{% endblock %}

efs/portfolio/templates/portfolio/investment_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Investment</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

efs/portfolio/templates/portfolio/portfolio.html
{% extends 'portfolio/base.html' %}
{% load humanize %}
{% block content %}

    <html>
            <head>
                <meta charset="UTF-8">
                <title>Eagle Financial</title>
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

            </head>

            <body>
                     <div class="container">
                                <div class="row">
                                    <div class="col-md-10 col-md-offset-1">
                                        <div class="panel panel-primary">
                                            <div class="panel-heading">Welcome!</div>
                                            <div class="panel-body">
                                                Eagle Financial Services, your Midwest Financial Services Partner.
                                            </div>
                                        </div>
                                    </div>
                               </div>

</div>
        <div class="row">
            <h1 style="padding-left: 15Px">Customer Portfolio</h1>
        </div>

        <div class="row">
            <h2 style="padding-left: 15Px">Stocks Information</h2>
        </div>
        <div class="row">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr class="bg-info">
                    <th>Customer</th>
                    <th>Symbol</th>
                    <th>Name</th>
                    <th>Shares</th>
                    <th>Initial Stock Price</th>
                    <th>Initial Stock Value</th>
                    <th>Current Stock Price</th>
                    <th>Current Stock Value</th>
                    <th>Results USD</th>
                    <th>Results INR</th>
                    <th>Results GBP</th>

                </tr>
                </thead>
                <tbody>
                {% for stock in stocks %}
                    <tr>
                        <td>{{ stock.customer }}</td>
                        <td>{{ stock.symbol }}</td>
                        <td>{{ stock.name }}</td>
                        <td>{{ stock.shares|intcomma }}</td>
                        <td>{{ stock.purchase_price|intcomma }}</td>
                        <td>{{ stock.initial_stock_value|intcomma}}</td>
                        <td>{{ stock.current_stock_price|intcomma}}</td>
                        <td>{{ stock.current_stock_value|intcomma}}</td>
                        <td>{{ stock.result|intcomma}}</td>
                        <td>{{ stock.result_indianrupee|intcomma}}</td>
                        <td>{{ stock.result_gbp|intcomma}}</td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="row">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr class="bg-info">
                    <th>Total of Initial Stocks</th>
                    <th>Total of Current Stocks</th>
                    <th>Results</th>

                </tr>
                </thead>
                <tbody>
                <tr>
                        <td>{{ sum_of_initial_stock_value|intcomma }}</td>
                        <td>{{ sum_current_stocks_value|intcomma }}</td>
                        <td>{{ sum_of_result_of_stock_value|intcomma }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="row">
            <h2 style="padding-left: 15Px">Investment Information</h2>
        </div>
        <div class="row">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr class="bg-info">
                    <th>Customer Number</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Acquired Value</th>
                    <th>Acquired Date</th>
                    <th>Recent Value</th>
                    <th>Recent Date</th>
                    <th>Results USD</th>
                    <th>Results INR</th>
                    <th>Results GBP</th>
                </tr>
                </thead>
                <tbody>
                {% for investment in investments %}
                    <tr>
                        <td>{{ investment.customer }}</td>
                        <td>{{ investment.category }}</td>
                        <td>{{ investment.description }}</td>
                        <td>{{ investment.acquired_value|intcomma }}</td>
                        <td>{{ investment.acquired_date }}</td>
                        <td>{{ investment.recent_value|intcomma }}</td>
                        <td>{{ investment.recent_date }}</td>
                        <td>{{ investment.result|intcomma}}</td>
                        <td>{{ investment.result_indianrupee|intcomma}}</td>
                        <td>{{ investment.result_gbp|intcomma}}</td>
                        </td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
         <div class="row">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                <tr class="bg-info">
                    <th>Total of Initial Investments</th>
                    <th>Total of Current Investments</th>
                    <th>Results</th>

                </tr>
                </thead>
                <tbody>
                <tr>
                        <td>{{ sum_of_initial_investment_value|intcomma }}</td>
                        <td>{{ sum_current_investment_value|intcomma }}</td>
                        <td>{{ sum_of_result_of_investment_value|intcomma }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="row">
<!--                <a href="{% url 'portfolio:investment_new' %}"><span-->
<!--                        class="btn btn-primary">Add Investment</span></a>-->
                <a href="{% url 'portfolio:broadcast' pk=customerid phonenumber=customer_phoneNumber initalstock=sum_of_initial_stock_value currentstock=sum_current_stocks_value initalinvestment=sum_of_initial_investment_value currentinvestment=sum_current_investment_value %}"><span
                        class="btn btn-primary">Send SMS Notification</span></a>
                <a href="{% url 'portfolio:sendpdfEmail' pk=customerid %}"><span
                        class="btn btn-primary">Send Email</span></a>
                <a href="{% url 'portfolio:downloadPDF' pk=customerid %}"><span
                            class="btn btn-primary">Download PDF</span></a>
        </div>
        <br>
        <br>
        <br>
    </body>
</html>
{% endblock %}

efs/portfolio/templates/portfolio/reset_password.html
{% extends "portfolio/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Reset Password{% endblock %}

{% block content %}
<h4>Please specify your email address to receive instructions for resetting it.</h4>

<form action="" method="post">
    <div style="display:none">
        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    </div>
     {{ form.email.errors}}
    <p><label form ="id_email">E-mail address:</label> {{ form.email }} <input type="submit" class="save btn btn-primary" value="Reset password" /></p>
</form>
{% endblock %}

efs/portfolio/templates/portfolio/reset_password_complete.html
{% extends "portfolio/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Password reset complete{% endblock %}

{% block content %}
<h3>Your password has been set.  You may go ahead and log in now.</h3>
<p><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></p>
{% endblock %}

efs/portfolio/templates/portfolio/reset_password_done.html
{% extends "portfolio/base.html" %}

{% block title %}Password reset successful{% endblock %}

{% block content %}
<p>We've e-mailed you instructions for setting your password to the e-mail address you submitted.</p>
<p>You should be receiving it shortly.</p>
{% endblock %}

efs/portfolio/templates/portfolio/signup.html
{% extends 'portfolio/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Sign Up{% endblock title %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Sign Up</button>
</form>
{% endblock content %}

efs/portfolio/templates/portfolio/stock_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Stock</h1>
    <form method="POST" class="stock-form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}